# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      os: 'linux'
      imageName: 'ubuntu-latest'
    mac:
      os: 'osx'
      imageName: 'ubuntu-latest'
    windows:
      os: 'windows'
      imageName: 'ubuntu-latest'
    arm32v7:
      os: 'arm32v7'
      imageName: 'arm64'

pool:
  vmImage: $(imageName)

variables:
  - group: AWS Variables
  - name: scripts
    value: $(build.SourcesDirectory)/.github/scripts
#  - name: AWS_S3_ENABLE
#    value:  $(AWS_S3_ENABLE)

steps:
- script: |
          env
          echo ""
          echo "listing of build.SourcesDirectory"
          ls $(build.SourcesDirectory)
  displayName: 'Dump Environment'

- script: sudo ${{variables.scripts}}/00-install-deps.sh $(os)
  displayName: 'Install Build Tools'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
